swagger: '2.0'
info:
  title: Product API
  description: API for accessing product information
  version: 1.0.0
schemes:
  - https
paths:
  /products:
    get:
      summary: Returns a list of products
      operationId: getProducts
      x-google-backend:
        address: URL-CLOUD-FUNCTION
      responses:
        '200':
          description: A JSON array of product names
          schema:
            type: array
            items:
              type: object
              properties:
                id:
                  type: integer
                name:
                  type: string
                price:
                  type: number