def serverless_website(request):
    headers = {
        'Content-Type': 'text/html; charset=utf-8'
    }
    html_content = """
    <!DOCTYPE html>
    <html>
    <head>
        <title>Simple HTML Site</title>
        <style>
            body { font-family: Arial, sans-serif; margin: 0; padding: 0; background-color: #f4f4f4; }
            .container { max-width: 800px; margin: 0 auto; padding: 20px; background-color: #fff; box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1); }
            h1 { color: #003366; }
            p { color: #666; }
            a { color: #FF9966; text-decoration: none; }
            a:hover { text-decoration: underline; }
        </style>
    </head>
    <body>
        <div class="container">
            <h1>Welcome to Your Simple Site!</h1>
            <p>This site is generated by a Google Cloud Function.</p>
            <p>Learn more about <a href="https://cloud.google.com/functions" target="_blank">Google Cloud Functions</a>.</p>
        </div>
    </body>
    </html>
    """
    return html_content, 200, headers
